### ISSUE TITLE
readability issue on excluded folders

### ISSUE THREAD

**Issue by euri10** [ShiromMakkad/base16-jetbrains-ide#1]
I'm not sure where in the ide settings this should be, see this

![20210601_1035_396x272_1622536532](https://user-images.githubusercontent.com/1104190/120293056-30eb3980-c2c5-11eb-815f-7456b452c21b.png)

the folder is red because when you right click it you can mark it as Excluded

**Comment by euri10** [comment]
one solution is this btw, not sure if this needs to be fixed here: https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-549154675

**Comment by r4j4h** [comment]
not sure where this should go but it seems related to this, so I wanted to emphasize this proposed solution on the official plugins reviews: https://imgur.com/r7G5WgX from https://plugins.jetbrains.com/plugin/10321-nord/reviews#review=53562-53563

**Comment by ShiromMakkad** [comment]
Can you try it now? I redid the themes. If it doesnt work, I don't think there's a good way to do this across base16 themes. Honestly I'm having a hard time dealing with text across multiple themes so I'll probably just disable the file background colors.
