### ISSUE TITLE
Joining tinted-theming

### ISSUE THREAD

**Issue by JamyGolden** [ShiromMakkad/base16-jetbrains-ide#3]
Hi @ShiromMakkad @kkirss, I'm part of [Tinted Theming], an org continuing the development of the base16 work Chris began initially. You can read more about the formation of the organization here: https://github.com/tinted-theming/home/issues/51

[base16-jetbrains] is currently in the organisation and I'm busy looking at updating it to contain styling for the full jetbrains IDE. Since this is essentially what you've done, would you be interested in moving this repo to the [Tinted Theming] organization, perhaps moving this repos commits into [base16-jetbrains] and you two continuing to maintain it?

[Tinted Theming]: https://github.com/tinted-theming
[base16-jetbrains]: https://github.com/tinted-theming/base16-jetbrains

**Comment by ShiromMakkad** [comment]
This seems like a good idea for users. What do I need to do?

**Comment by JamyGolden** [comment]
Great! I've added you and  @kkirss as members to the organisation in the jetbrains team (so you'll also have maintain access to the other repo). You can transfer this repository to the org (repo Settings -> Transfer).

As for base16-jetbrains vs base16-jetbrains-ide. What are your thoughts on how to go about the two repos? Merge them? Keep separate?

**Comment by JamyGolden** [comment]
If you want to keep this repo under your name, we could also merge the repos into base16-jetbrains (bring the commits across), while you archive this one. (base16-jetbrains has more stars so if you think merging is the way, then moving into that repo would probably be a good idea)

**Comment by ShiromMakkad** [comment]
Yea, most jetbrains themes keep the editor and full ide theme as a single plugin, so I think it's best to move into base16-jetbrains as a single unified repo. 

Let's archive this repo and move my commits into the base16-jetbrains repo. Couple questions:

- When the commits get moved, will my name and history be preserved? Id like to keep that. 
- Will I have edit permissions on base16-jetbrains? Id like to be able to make branches and merge my prs.

**Comment by JamyGolden** [comment]
Yes your name will be preserved on the commits. The “move” of the commits isn’t as much of a “move” as it is copying the commits. I’ll do it tomorrow on a temporary branch and once you’re happy with it I can make the main branch reflect the changes. 

You should have maintainer access to base16-jetbrains right now, but yes that will continue to be the case after I’ve copied your commits across.

**Comment by JamyGolden** [comment]
I've pushed a new branch to base16-jetbrains which contains basd16-jetbrains commits with base16-jetbrains-ide commits put on top of it (so the commits follow chronologically). [Have a look at the branch](https://github.com/tinted-theming/base16-jetbrains/commits/new-main/) (titled `new-main` temporarily) and let me know if there is anything you want to change. Your commits have you marked as the original author and has me marked as someone who has edited the commit (since I'm the one who was doing the rebasing and resolving the conflicts). Github uses the date edited as the date shown, but if you have a look at the commit in git, it shows both the date created and date edited.

**Comment by ShiromMakkad** [comment]
Not sure why Github is showing just my email instead of my profile on that commit. It's doing the same on this repo for only the latest commit. Maybe I didn't have my git username set properly? Any way to fix?

**Comment by JamyGolden** [comment]
I've removed the image so your email isn't on the page. It's something you have to change in your github settings (the email that is put onto the commits). Any commits you've made in the past actually has your email currently attached to it and changing the settings only affects future commits. `git config --global user.email` is the email value used on commits you make.

Github doesn't show the emails, but if you checkout someone's repo and look at the author of the commits you more often than not see their real email address.

**Comment by JamyGolden** [comment]
I haven't done it before, but I could try to replace your email with a different value on the branch I made if you want? But note: your email is currently on the commits on this repo at the moment (and on any commit you've ever done on github I'd imagine)

**Comment by ShiromMakkad** [comment]
I'm ok with my email being attached to every commit, but if you look at the git history of this repo you'll see the issue is here too. It's not linking to my Github profile and name properly. It says "shirmak11@gmail.com authored" instead of "ShiromMakkad authored" Looking into this rn.

**Comment by JamyGolden** [comment]
My guess is that you made that specific commit from another computer or a computer which wasn't set up properly (maybe new computer?)

Your git username is set as your email value and your email is set to `shirom@Shirom-PC.localdomain` , so github doesn't know how to map that to your github account, since that email (not a real email) isn't related to your github account.

**Comment by JamyGolden** [comment]
I've adjusted your username and email on that specific commit on the branch on base16-jetbrains: https://github.com/tinted-theming/base16-jetbrains/commits/new-main/

**Comment by ShiromMakkad** [comment]
Perfect, I've got it fixed in this repo too. LGTM!

**Comment by ShiromMakkad** [comment]
Some changes will need to be made to combine the two repos. Also, the Readme will need to be updated with new installation instructions. I can work on that.

**Comment by JamyGolden** [comment]
Ok great, you can push changes directly to the `new-main` branch. We can replace `main` branch with `new-main` once it's good enough for users to look at.

**Comment by ShiromMakkad** [comment]
One thing, I'm looking at: https://github.com/tinted-theming/schemes/blob/spec-0.11/base16/tomorrow-night-eighties.yaml and I'm not seeing slugs for any themes. Has that been deprecated? What will be filled in when I put `{{scheme-slug}}` in a template?

**Comment by JamyGolden** [comment]
I've just generated the themes with base16-builder-go (the only builder that implements spec 0.11 at the moment) and pushed to `new-main`. I'll add a github action to run the builder on the repo every week so it's up to date with the latest schemes.

**Comment by JamyGolden** [comment]
Just adding in case it's of interest to you, we have a tinted-theming channel on Matrix if you prefer DMs https://matrix.to/#/#tinted-theming:matrix.org

**Comment by JamyGolden** [comment]
You mentioned that the readme needs to be updated and some other changes to combine the repos, which changes are you referring to? Things look quite similar on the `new-main` branch: https://github.com/tinted-theming/base16-jetbrains/tree/new-main

**Comment by JamyGolden** [comment]
Since the "installation" instructions are the same on [new-main](https://github.com/tinted-theming/base16-jetbrains/tree/new-main) I'm going point `main` branch there and complete the transition. Any other changes (to the readme or anything else) can happen afterwards.

**Comment by JamyGolden** [comment]
https://github.com/tinted-theming/base16-jetbrains now reflects the update. I suggest putting your repo in archive mode with a deprecation notice pointing to https://github.com/tinted-theming/base16-jetbrains as the new maintained version. You're a maintainer on that repo, we can discuss things on issues there or on our [Matrix channel](https://matrix.to/#/#tinted-theming:matrix.org). I'll close this github issue now.
